# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Soda_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Soda_iOS
pod 'Alamofire', '~> 5.5'
pod 'Kingfisher', '~> 7.0'


  target 'Soda_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Soda_iOSUITests' do
    # Pods for testing
  end

end
